"""Render an interactive Leaflet preview for evening-side stop offsets.

The input CSV is generated by ``generate_evening_stop_offsets.py``. This
script performs no database access and writes only the standalone HTML preview.
"""

from __future__ import annotations

import csv
import html
import json
from pathlib import Path


BACKEND_ROOT = Path(__file__).resolve().parents[1]
INPUT_CSV = BACKEND_ROOT / "scripts" / "evening_stop_offsets_preview.csv"
OUTPUT_HTML = BACKEND_ROOT / "scripts" / "evening_stop_offsets_preview.html"


def as_float(value: str | None) -> float | None:
    try:
        return float(value) if value not in (None, "") else None
    except ValueError:
        return None


def load_rows() -> list[dict[str, object]]:
    with INPUT_CSV.open("r", newline="", encoding="utf-8") as csv_file:
        rows: list[dict[str, object]] = []
        for row in csv.DictReader(csv_file):
            rows.append(
                {
                    "stop_id": row["stop_id"],
                    "stop_name": row["stop_name"],
                    "route_id": row["route_id"],
                    "original_lat": as_float(row["original_lat"]),
                    "original_lng": as_float(row["original_lng"]),
                    "computed_evening_lat": as_float(row["computed_evening_lat"]),
                    "computed_evening_lng": as_float(row["computed_evening_lng"]),
                    "offset_distance_meters_actual": as_float(row["offset_distance_meters_actual"]),
                }
            )
    return rows


def build_html(rows: list[dict[str, object]]) -> str:
    data_json = json.dumps(rows, ensure_ascii=False).replace("</", "<\\/")
    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>KAMBUS Evening Stop Offset Preview</title>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
  <style>
    html, body, #map { height: 100%; margin: 0; }
    .legend { background: white; padding: 10px 12px; border-radius: 6px; box-shadow: 0 1px 5px rgba(0,0,0,.25); font: 13px/1.45 Arial, sans-serif; }
    .legend span { display: inline-block; width: 10px; height: 10px; margin-right: 6px; border-radius: 50%; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
  <script>
    const rows = __DATA__;
    const map = L.map("map");
    L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png", {
      maxZoom: 19,
      attribution: "&copy; OpenStreetMap contributors &copy; CARTO"
    }).addTo(map);

    const bounds = [];
    const escapeHtml = value => String(value ?? "").replace(/[&<>\"']/g, character => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", "\\\"": "&quot;", "'": "&#039;"
    }[character]));

    rows.forEach(row => {
      if (!Number.isFinite(row.original_lat) || !Number.isFinite(row.original_lng)) return;

      const original = [row.original_lat, row.original_lng];
      const distance = Number.isFinite(row.offset_distance_meters_actual)
        ? `${row.offset_distance_meters_actual.toFixed(2)} m`
        : "not computed";
      const popup = `<strong>${escapeHtml(row.stop_name)}</strong><br>` +
        `Stop ID: ${escapeHtml(row.stop_id)}<br>` +
        `Route ID: ${escapeHtml(row.route_id)}<br>` +
        `Offset distance: ${distance}`;

      L.circleMarker(original, {
        radius: 6, color: "#1d4ed8", fillColor: "#2563eb", fillOpacity: 0.9, weight: 2
      }).addTo(map).bindPopup(`Original stop<br>${popup}`);
      bounds.push(original);

      if (!Number.isFinite(row.computed_evening_lat) || !Number.isFinite(row.computed_evening_lng)) return;

      const evening = [row.computed_evening_lat, row.computed_evening_lng];
      L.polyline([original, evening], { color: "#64748b", weight: 1, opacity: 0.8 }).addTo(map);
      L.circleMarker(evening, {
        radius: 6, color: "#b91c1c", fillColor: "#ef4444", fillOpacity: 0.9, weight: 2
      }).addTo(map).bindPopup(`Evening offset<br>${popup}`);
      bounds.push(evening);
    });

    if (bounds.length) map.fitBounds(bounds, { padding: [30, 30] });
    else map.setView([18.054145, 79.535587], 13);

    const legend = L.control({ position: "topright" });
    legend.onAdd = () => {
      const container = L.DomUtil.create("div", "legend");
      container.innerHTML = "<div><span style='background:#2563eb'></span>Original stop</div>" +
        "<div><span style='background:#ef4444'></span>Evening offset</div>" +
        "<div style='margin-top:5px;color:#475569'>Thin line = offset pair</div>";
      return container;
    };
    legend.addTo(map);
  </script>
</body>
</html>
""".replace("__DATA__", data_json)


def main() -> None:
    rows = load_rows()
    OUTPUT_HTML.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_HTML.write_text(build_html(rows), encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {OUTPUT_HTML}")


if __name__ == "__main__":
    main()
